import type { ITheme } from "@xterm/xterm";

export interface TermTheme {
  id: string;
  name: string;
  theme: ITheme;
}

// Open-source 16-colour schemes mapped to the xterm.js ITheme shape.
// Sources: Tapterm (default), Dracula, Nord, Tokyo Night, Catppuccin Mocha,
// Gruvbox Dark, One Dark, Solarized Dark — all permissively licensed.
export const THEMES: TermTheme[] = [
  {
    id: "tapterm",
    name: "Tapterm (default)",
    theme: {
      background: "#0B1220",
      foreground: "#E2E8F0",
      cursor: "#818CF8",
      cursorAccent: "#0B1220",
      selectionBackground: "#6366F140",
      black: "#1E293B",
      red: "#F43F5E",
      green: "#22C55E",
      yellow: "#FBBF24",
      blue: "#38BDF8",
      magenta: "#A78BFA",
      cyan: "#2DD4BF",
      white: "#E2E8F0",
      brightBlack: "#475569",
      brightRed: "#FB7185",
      brightGreen: "#4ADE80",
      brightYellow: "#FCD34D",
      brightBlue: "#7DD3FC",
      brightMagenta: "#C4B5FD",
      brightCyan: "#5EEAD4",
      brightWhite: "#F8FAFC",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    theme: {
      background: "#282A36",
      foreground: "#F8F8F2",
      cursor: "#F8F8F2",
      cursorAccent: "#282A36",
      selectionBackground: "#44475A",
      black: "#21222C",
      red: "#FF5555",
      green: "#50FA7B",
      yellow: "#F1FA8C",
      blue: "#BD93F9",
      magenta: "#FF79C6",
      cyan: "#8BE9FD",
      white: "#F8F8F2",
      brightBlack: "#6272A4",
      brightRed: "#FF6E6E",
      brightGreen: "#69FF94",
      brightYellow: "#FFFFA5",
      brightBlue: "#D6ACFF",
      brightMagenta: "#FF92DF",
      brightCyan: "#A4FFFF",
      brightWhite: "#FFFFFF",
    },
  },
  {
    id: "nord",
    name: "Nord",
    theme: {
      background: "#2E3440",
      foreground: "#D8DEE9",
      cursor: "#D8DEE9",
      cursorAccent: "#2E3440",
      selectionBackground: "#434C5E",
      black: "#3B4252",
      red: "#BF616A",
      green: "#A3BE8C",
      yellow: "#EBCB8B",
      blue: "#81A1C1",
      magenta: "#B48EAD",
      cyan: "#88C0D0",
      white: "#E5E9F0",
      brightBlack: "#4C566A",
      brightRed: "#BF616A",
      brightGreen: "#A3BE8C",
      brightYellow: "#EBCB8B",
      brightBlue: "#81A1C1",
      brightMagenta: "#B48EAD",
      brightCyan: "#8FBCBB",
      brightWhite: "#ECEFF4",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    theme: {
      background: "#1A1B26",
      foreground: "#C0CAF5",
      cursor: "#C0CAF5",
      cursorAccent: "#1A1B26",
      selectionBackground: "#283457",
      black: "#15161E",
      red: "#F7768E",
      green: "#9ECE6A",
      yellow: "#E0AF68",
      blue: "#7AA2F7",
      magenta: "#BB9AF7",
      cyan: "#7DCFFF",
      white: "#A9B1D6",
      brightBlack: "#414868",
      brightRed: "#F7768E",
      brightGreen: "#9ECE6A",
      brightYellow: "#E0AF68",
      brightBlue: "#7AA2F7",
      brightMagenta: "#BB9AF7",
      brightCyan: "#7DCFFF",
      brightWhite: "#C0CAF5",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    theme: {
      background: "#1E1E2E",
      foreground: "#CDD6F4",
      cursor: "#F5E0DC",
      cursorAccent: "#1E1E2E",
      selectionBackground: "#585B70",
      black: "#45475A",
      red: "#F38BA8",
      green: "#A6E3A1",
      yellow: "#F9E2AF",
      blue: "#89B4FA",
      magenta: "#F5C2E7",
      cyan: "#94E2D5",
      white: "#BAC2DE",
      brightBlack: "#585B70",
      brightRed: "#F38BA8",
      brightGreen: "#A6E3A1",
      brightYellow: "#F9E2AF",
      brightBlue: "#89B4FA",
      brightMagenta: "#F5C2E7",
      brightCyan: "#94E2D5",
      brightWhite: "#A6ADC8",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    theme: {
      background: "#282828",
      foreground: "#EBDBB2",
      cursor: "#EBDBB2",
      cursorAccent: "#282828",
      selectionBackground: "#504945",
      black: "#282828",
      red: "#CC241D",
      green: "#98971A",
      yellow: "#D79921",
      blue: "#458588",
      magenta: "#B16286",
      cyan: "#689D6A",
      white: "#A89984",
      brightBlack: "#928374",
      brightRed: "#FB4934",
      brightGreen: "#B8BB26",
      brightYellow: "#FABD2F",
      brightBlue: "#83A598",
      brightMagenta: "#D3869B",
      brightCyan: "#8EC07C",
      brightWhite: "#EBDBB2",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    theme: {
      background: "#282C34",
      foreground: "#ABB2BF",
      cursor: "#528BFF",
      cursorAccent: "#282C34",
      selectionBackground: "#3E4451",
      black: "#282C34",
      red: "#E06C75",
      green: "#98C379",
      yellow: "#E5C07B",
      blue: "#61AFEF",
      magenta: "#C678DD",
      cyan: "#56B6C2",
      white: "#ABB2BF",
      brightBlack: "#5C6370",
      brightRed: "#E06C75",
      brightGreen: "#98C379",
      brightYellow: "#E5C07B",
      brightBlue: "#61AFEF",
      brightMagenta: "#C678DD",
      brightCyan: "#56B6C2",
      brightWhite: "#FFFFFF",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    theme: {
      background: "#002B36",
      foreground: "#839496",
      cursor: "#93A1A1",
      cursorAccent: "#002B36",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#DC322F",
      green: "#859900",
      yellow: "#B58900",
      blue: "#268BD2",
      magenta: "#D33682",
      cyan: "#2AA198",
      white: "#EEE8D5",
      brightBlack: "#002B36",
      brightRed: "#CB4B16",
      brightGreen: "#586E75",
      brightYellow: "#657B83",
      brightBlue: "#839496",
      brightMagenta: "#6C71C4",
      brightCyan: "#93A1A1",
      brightWhite: "#FDF6E3",
    },
  },
];

export function themeById(id: string): ITheme {
  return (THEMES.find((t) => t.id === id) ?? THEMES[0]).theme;
}
